name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "your-username"
          git remote add space https://huggingface.co/spaces/yudarahma/praktekcloud
          git fetch space
          git push --force space main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
